packages/dev-frontend/src/components/RiskyTroves.tsx
packages/dev-frontend/src/components/SystemStats.tsx
packages/dev-frontend/src/components/Trove/CollateralRatio.tsx

- red font when CR is 120% or less
- add always visible Recovery Mode stat (with tooltip for extra info)
- add information box to Trove panel which explains that a CR above 150% is better for avoiding liquidation

devui: clarify recovery mode where possible

---

README.public.md

Include deprecation notice in README and point people at the live codebase.

Deprecate liquity/liquity repo

---

packages/subgraph/schema.graphql
packages/subgraph/src/entities/Global.ts
packages/subgraph/src/entities/StabilityDeposit.ts
packages/subgraph/src/entities/Trove.ts
packages/subgraph/src/entities/User.ts
packages/subgraph/subgraph.yaml

Previously, we would create a new Trove entity whenever a user called openTrove() after a closeTrove() or a liquidation/redemption. This would make it more complicated to reconstruct a "unified" Trove history, because the frontend would have to stitch together the histories of multiple Trove entities.
Let's change this so the existing Trove entity is reused when the user reopens their Trove.
Same for StabilityDeposits: we would consider the deposit "closed" when its LUSD balance would fall to 0, and create a new entity upon the next deposit event. Let's just reuse the existing entity instead.

feat!: have only one Trove/StabilityDeposit per User

---

packages/dev-frontend/src/components/Farm/context/FarmViewProvider.tsx
packages/dev-frontend/src/components/Farm/context/transitions.ts
packages/dev-frontend/src/components/Farm/views/Active/Active.tsx

Currently a user can reduce their UNI LP to 0, which the UI then incorrectly assumes means there's no rewards to be claimed.

devui: allow user to claim gains after unstaking UNI LP

---

packages/dev-frontend/src/App.test.tsx
packages/dev-frontend/src/components/Trove/Adjusting.tsx
packages/dev-frontend/src/components/Trove/Opening.tsx
packages/dev-frontend/src/components/Trove/Trove.tsx
packages/dev-frontend/src/components/Trove/TroveEditor.tsx
packages/dev-frontend/src/components/Trove/validation/validateTroveChange.tsx

- Introduce Opening view for the OPENING state
- Introduce Adjusting view for the ADJUSTING state
- Ask user for a borrow amount instead of total debt when OPENING
- Ask user for a new net debt amount instead of a total debt when ADJUSTING

devui: choose borrow amount when opening trove and net debt when adjusting a trove

---

packages/dev-frontend/src/components/Trove/Adjusting.tsx
packages/dev-frontend/src/components/Trove/Opening.tsx
packages/dev-frontend/src/components/Trove/TroveEditor.tsx

- Set min borrow amount to 1800 to compensate for fee decay factor
- Apply unsaved Trove adjustments to changes from the backend (e.g. debt redistribution or partial redemption)
- Handle Trove closed event (only render component if trove is `open`)

devui: update min borrow amount and sync backend changes

---

packages/subgraph/schema.graphql
packages/subgraph/src/mappings/StabilityPool.ts

They used to always come in the order of:
1. ETHGainWithdrawn
2. UserDepositUpdated
At some point the order was swapped in _some_ StabilityPool functions,
but not all of them.
Let's virtually restore the original order in the subgraph mappings.
Fixes #499

fix: untangle StabilityDeposit events in subgraph

---

packages/subgraph/src/entities/Trove.ts
packages/subgraph/src/mappings/BorrowerOperations.ts
packages/subgraph/src/mappings/TroveManager.ts
packages/subgraph/subgraph.yaml.js

The issue was introduced when capped liquidations were added to the backend.
Up until then, the `_coll` and `_debt` parameters of `TroveLiquidated` events
reflected the final state of the Trove immediately before the liquidation.
The subgraph relied on this to insert an `accrueRewards` operation in case
there have been redistributions between the last Trove adjustment and the
liquidation. However, in the case of a capped liquidation, `_coll` now reflects
the capped portion of the collateral that's liquidated, so we can no longer
rely on the event's parameters.
Instead, we should calculate the redistribution from the Trove's snapshots,
stake and the global redistribution counters.
Fixes #580.

fix: eliminate bogus `TroveChange` upon capped liquidation

---

packages/contracts/contracts/TestContracts/PriceFeedTestnet.sol
packages/lib-subgraph/apollo.config.js
packages/lib-subgraph/src/SubgraphLiquity.ts
packages/lib-subgraph/types/Global.ts
packages/lib-subgraph/types/TroveWithoutRewards.ts
packages/subgraph/schema.graphql
packages/subgraph/src/calls/PriceFeed.ts
packages/subgraph/src/entities/Change.ts
packages/subgraph/src/entities/Global.ts
packages/subgraph/src/entities/LqtyStake.ts
packages/subgraph/src/entities/StabilityDeposit.ts
packages/subgraph/src/entities/SystemState.ts
packages/subgraph/src/entities/Transaction.ts
packages/subgraph/src/entities/Trove.ts
packages/subgraph/src/entities/User.ts
packages/subgraph/src/mappings/PriceFeed.ts
packages/subgraph/src/mappings/TroveManager.ts
packages/subgraph/src/utils/bignumbers.ts
packages/subgraph/subgraph.yaml.js

Previously, price was checked via `eth_call` upon creating a new Transaction entity.
The problem is that calls see the blockchain state after all the transactions in the
current block have been executed. This means if there was a Liquity TX mined in the
same block as a (Chainlink) price update, but ordered _before_ the price update, the
subgraph would prematurely use the updated price to calculate ICRs while processing
the Liquity TX.
Instead of calling the PriceFeed, use its event `LastGoodPriceUpdated`, which is
correctly ordered with regard to other Liquity events.
Fixes #581.

Fix price in subgraph

---

packages/subgraph/src/entities/SystemState.ts
packages/subgraph/src/utils/bignumbers.ts
packages/subgraph/src/utils/collateralRatio.ts

Total collateral was incorrect after a redistribution, because we weren't subtracting the 0.5% collateral paid out as gas compensation.
Fixes #591.

Fix total collateral in subgraph

---

packages/dev-frontend/src/components/Trove/validation/validateTroveChange.tsx

This prevents sending TXs that are at risk of failing due to decrease of the
borrowing rate (either through decay or entering recovery mode).
This also fixes a problem where the confirm button on the Trove panel could
get stuck if trying to open a Trove with dangerously low debt. The fee decay
estimation logic would throw an error upon seeing the Trove's debt decay
below the minimum within the fee decay tolerance period.
Fixes #613.

fix: require borrowing at least the minimum net debt

---

packages/providers/src/WebSocketAugmentedProvider.ts

Previously, an error thrown from a listener function would cause the
dispatch of the event to prematurely stop, resulting in not all listeners
being notified.
Ethers solves this by deferring listener invocation to the next event cycle
using `setTimeout()`. Let's do the same.

fix: don't let listener errors mess up event dispatch

---

packages/contracts/hardhat.config.js
packages/contracts/mainnetDeployment/balancerDeploymentOutput/balancerOutput_20210629.txt
packages/contracts/mainnetDeployment/balancerPoolDeployment.js

- Add gas logs.
- Change initial funding to 15k.
- Allow to pass an already deployed address as an env variable to make
it more resilient.
- Allow to pass gas price as an env variable for mainnet config.
- Add Balancer deployment output file.

contracts: Balancer pool deployment last tweaks

---

packages/lib-ethers/src/PopulatableEthersLiquity.ts
packages/lib-ethers/test/Liquity.test.ts

The problem:
> [...] for the last trove in the list, the addressOfLowestICRTrove is their own address - and the reinsertion first removes it before the insert. The system can't find it in the list, so starts at the opposite end, and runs out of gas.
DefiSaver's original workaround:
> [...] check for this specific edge case: if the trove is last in the list, use the 2nd last trove's address as both hints.
This implements a generalized version of that workaround:
* In either of the hints is the user's own Trove, "jump over" it and replace it with the next/prev Trove.
* If either of the hints is `address(0)`, replace it with the other hint.
Fixes #659.

fix: work around huge gas cost when reducing ICR of bottom Trove

---

packages/contracts/contracts/TroveManager.sol

The initial fix was wrong, as now for case of ICR between 100% and
MCR, collToOffset would be zero, so it wouldn’t be subtracted.
Besides, subtracting the gas compensation too, which in that case was
missed too.

contracts: Fix back to Normal Mode issue in multi-liquidations

---

.gitattributes

fix(.gitattributes): prevent github from showing json comments as errors

---

packages/dev-frontend/src/components/Stability/Yield.tsx
packages/dev-frontend/src/components/Stability/context/fetchLqtyPrice.ts

The way we used to calculate it is akin to calculating the average APR you would get if you stayed in the pool for one year (while the price of LQTY and the LUSD deposited in SP stayed constant).
Instead, let's calculate the current daily yield of the pool and annualize that via multiplying by 365, which is more in line with expectations.

Calculate LQTY reward APR based on current daily LQTY issuance

---

packages/dev-frontend/src/App.test.tsx
packages/dev-frontend/src/App.tsx
packages/dev-frontend/src/components/AppLoader.tsx
packages/dev-frontend/src/components/Bonds/Bonds.tsx
packages/dev-frontend/src/components/Bonds/Record.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewContext.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewProvider.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/context/useBondContracts.tsx
packages/dev-frontend/src/components/Bonds/views/actioning/actions/cancel/Cancel.tsx
packages/dev-frontend/src/components/Bonds/views/actioning/actions/claim/Claim.tsx
packages/dev-frontend/src/components/Bonds/views/idle/BondList.tsx
packages/dev-frontend/src/components/Bonds/views/idle/FilteredBondList.tsx
packages/dev-frontend/src/components/Bonds/views/idle/Idle.tsx
packages/dev-frontend/src/components/Bonds/views/idle/OptimisticBond.tsx
packages/dev-frontend/src/components/Bonds/views/idle/actions/Actions.tsx
packages/dev-frontend/src/components/HorizontalTimeline.tsx
packages/dev-frontend/src/components/Placeholder.tsx
packages/dev-frontend/src/hooks/useContract.ts
packages/dev-frontend/src/setupTests.ts

- Refreshes every 15 seconds
- Updates whenever the backend is mutated (write operations: approve lusd, create/cancel/claim bond)
- Optimistically renders a new bond when its created, then updates the unknown values when the backend refreshes
- Optimistically removes or claims a bond before waiting for the backend values to refresh

Bonds UI: Add support for automatically refreshing backend values

---

packages/dev-frontend/src/components/Bonds/Bonds.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewContext.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewProvider.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/views/idle/Bond.tsx
packages/dev-frontend/src/components/Bonds/views/idle/Idle.tsx
packages/dev-frontend/src/components/Bonds/views/idle/OptimisticBond.tsx
packages/dev-frontend/src/components/Bonds/views/swapping/SwapPane.tsx
packages/dev-frontend/src/components/Bonds/views/swapping/Swapping.tsx
packages/dev-frontend/src/components/Icon.tsx

Adds the ability to swap bLUSD back and forth with LUSD without having to turn to the Curve frontend (which doesn't support testnets, preventing us from fully testing all aspects of LUSD Chicken Bonds).
Slippage handling. Currently, any amount of slippage is tolerated.
Ability to add/manage liquidity.
We might want to show price impact?

Buy & sell bLUSD within the frontend

---

packages/dev-frontend/src/components/Bonds/BondsTable.tsx
packages/dev-frontend/src/components/Bonds/Record.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewProvider.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/context/useBondContracts.tsx
packages/dev-frontend/src/components/Bonds/utils.ts
packages/dev-frontend/src/components/Bonds/views/actioning/Actioning.tsx
packages/dev-frontend/src/components/Bonds/views/creating/Details.tsx
packages/dev-frontend/src/components/Bonds/views/idle/Bond.tsx
packages/dev-frontend/src/components/Bonds/views/idle/Idle.tsx
packages/dev-frontend/src/components/Bonds/views/idle/OptimisticBond.tsx
packages/dev-frontend/src/components/HorizontalTimeline.tsx
packages/dev-frontend/src/components/Placeholder.tsx

Use the tokenURI from the bond NFT token.
Also:
- Fix rounding issues in bond time estimations.
- Use real NFT images from token data.
- Don't block the app from loading if there are no bonds.
- Don't block app from loading if there are negative values.
- Explicitly handle market price premium being less than 1
Next PR:
- Switch Goerli addresses to the latest: https://github.com/liquity/ChickenBond/blob/main/LUSDChickenBonds/bindings/deployments/goerli.json (fixes the Luchadore NFT image data formatting issue)

Bonds UI: Use real NFT images 

---

packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/views/actioning/Actioning.tsx
packages/dev-frontend/src/components/Bonds/views/creating/Details.tsx

Chicken-in fee wasn't taken into account. Also truncate percentages with a large number of decimals, as suggested by @cvalkan.

Fix incorrect accrued bLUSD values at milestones

---

packages/dev-frontend/src/components/Bonds/context/api.ts

`accrualParameter` is only updated in storage when there's user interaction, however all the read functions (like `calcAccruedBLUSD()`) internally calculate what alpha would be after an update, and use that in calculations. It makes sense for us to also base UI calculations on the predicted value.

fix: get the most up-to-date alpha

---

packages/dev-frontend/src/components/BondStats.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/lexicon.ts

Use Yearn to get yield rates of LUSD-3CRV and Stability Pool strategies, then use these rates to calculate bLUSD's APR and Yield amplification.
Example usage on our Goerli testnet game:

Add bLUSD APR and Yield amplification stat

---

packages/dev-frontend/src/components/Bonds/views/managing/PoolDetails.tsx
packages/dev-frontend/src/components/Bonds/views/managing/WithdrawPane.tsx
packages/dev-frontend/src/components/Bonds/views/swapping/SwapPane.tsx
packages/dev-frontend/src/components/Trove/Editor.tsx
packages/dev-frontend/src/theme.ts

Also add placeholders while swap output estimates are loading.
Looks like this:

feat: configurable slippage tolerance

---

packages/dev-frontend/src/components/Bonds/context/api.ts

Bonding indirectly triggers LQTY issuance, through interaction with the Stability Pool. The exact gas costs of this depend on the block timestamp of the block that eventually includes the TX, which is not know ahead of time. Therefore let's include some extra gas to ensure that the TX will succeed.

fix: bonding TXs sometimes running out of gas

---

packages/dev-frontend/src/components/BondStats.tsx
packages/dev-frontend/src/components/Bonds/lexicon.ts
packages/dev-frontend/src/components/Bonds/views/creating/Details.tsx

- Show APR/yield-amplification as N/A until bLUSD enters the market
- If the user has less than 100 LUSD and opens the create bond dialog, show the insufficient funds error immediately
- Remove reference to bLUSD/LUSD Curve pool since its now bLUSD/LUSD-3CRV

UI: Various changes picked up on mainnet deployment

---

packages/dev-frontend/src/components/Bonds/views/creating/Details.tsx

Tooltip changed to:
```The market price of bLUSD impacts how long it will take to rebond and break even. The actual times may be overestimated as the simulator is based on the current bLUSD accrual rate, not taking into account potential rate adjustments (see https://liquity.gitbook.io/chicken-bonds/faq/economic-design#_44lrt4qpho3a).```

Improve description of simulator

---

package.json
packages/dev-frontend/package.json

BigInt support is required from cryptography dependencies etc. so this PR makes browserslist versions compatible.
See:
https://github.com/paulmillr/noble-ed25519/issues/23#issuecomment-1109248320
https://github.com/0xs34n/starknet.js/issues/37#issuecomment-955797303

Update browserslist support 

---

packages/dev-frontend/src/components/Bonds/views/managing/DepositPane.tsx
packages/dev-frontend/src/components/Bonds/views/managing/PoolDetails.tsx

All functionality is aligned with how Curve manages it on their UI, except for unticking the checkbox. In Curve it resets the amount fields to 0, in ours it leaves it as the last values entered since I would have thought this would be the more common path. But happy to change it to also reset if its a better UX. (Ticking still resets as expected since that would otherwise be a misleading state).
----
----
----
----
C) ![image](https://user-images.githubusercontent.com/5167260/197007050-787ed30c-ca9b-46de-b087-70f67ef4c15a.png)

Enable user to deposit liquidity balanced and show balance ratio

---

packages/dev-frontend/src/components/Bonds/context/BondViewContext.tsx
packages/dev-frontend/src/components/Bonds/context/BondViewProvider.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts
packages/dev-frontend/src/components/Bonds/context/useBondContracts.tsx
packages/dev-frontend/src/components/Bonds/views/managing/ManagingLiquidity.tsx
packages/dev-frontend/src/components/Bonds/views/managing/PendingRewards.tsx
packages/dev-frontend/src/components/Bonds/views/managing/RewardsPane.tsx
packages/dev-frontend/src/components/Bonds/views/managing/StakePane.tsx
packages/dev-frontend/src/components/Bonds/views/managing/UnstakePane.tsx
packages/dev-frontend/src/components/InfoIcon.tsx
packages/dev-frontend/src/components/Trove/Editor.tsx

Enable viewing and claiming LP rewards

---

packages/dev-frontend/src/components/BondStats.tsx
packages/dev-frontend/src/components/Bonds/context/api.ts
packages/dev-frontend/src/components/Bonds/context/transitions.ts

No change:
- For bond stats show the floor price without Reserve pending harvests considered (to avoid the floor price appearing to go down)
Change:
- For bond estimations use the floor price "at next chicken in" value (since this is the value the smart contract uses)

Use current floor price for bonding calculations

---

README.md
packages/dev-frontend/src/components/Bonds/views/managing/WithdrawPane.tsx

Specify min out parameters for Curve liquidity withdrawals.

Fix bLUSD LP withdrawal sandwich attack

---

packages/contracts/contracts/Integrations/LSUDUsdToLUSDEth.sol
packages/contracts/hardhat.config.mainnet-fork.js
packages/contracts/mainnetDeployment/aaveEthOracleDeployment.js

Needed for AAVE integration.
Mainnet deployment here: https://etherscan.io/address/0x60c0b047133f696334a2b7f68af0b49d2f3d4f72#code
Adapted from ENS version: https://etherscan.io/address/0xd4641b75015E6536E8102D98479568D05D7123Db#code

Add USD to ETH Chainlink oracle connector for LUSD

---

README.md
packages/contracts/contracts/StabilityPool.sol

Replace #891 
The link, https://github.com/liquity/dev/blob/main/packages/contracts/mathProofs/Scalable%20Compounding%20Stability%20Pool%20Deposits.pdf, used in the comment of the StabilityPool.sol is broken. Thus, replace it with the valid link: https://github.com/liquity/dev/blob/main/papers/Scalable_Reward_Distribution_with_Compounding_Stakes.pdf
There is a mistake on description and a typo in the README.md.
One is that Ether in the system lives in four Pools plus LQTYStaking instead of three pools.
Another is that "deployent" is a typo.

doc: fix broken link, description and typo

---

.github/workflows/release.yml
.github/workflows/test-contracts.yml
package.json

Yarn v1 used to do this. Yarn v2 and later no longer do it, so let's add it back.

chore: automatically prepare after installation

---

package.json
packages/subgraph/package.json
packages/subgraph/subgraph.yaml.js
yarn.lock

The version of Graph CLI we were using could no longer be installed due to depending on a (deprecated) version of ipfs-http-client that in turn depended on a Github repo that had since been removed. See #1029.
By upgrading Graph tooling, we at least let the repo be installed via Yarn. However, the Liquity subgraph can't be compiled using the newer tooling: the AssemblyScript compiler crashes without an error message.
Fixing the subgraph build will thus be challenging, but in the meantime, let's unblock installation at least.

Upgrade Graph tooling but disable build
